# Generated by Django 5.2.3 on 2025-08-09 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_conversation_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedBug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.CharField(db_index=True, max_length=255)),
                ('error_category', models.CharField(blank=True, db_index=True, help_text='e.g., TypeError, ReferenceError, NameError', max_length=100, null=True)),
                ('original_code', models.TextField()),
                ('fix_step_count', models.PositiveSmallIntegerField(default=1)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_bugs', to='posts.language')),
                ('user', models.ForeignKey(blank=True, help_text='User who encountered the bug', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['logged_at', 'language'], name='posts_logge_logged__41ba5b_idx'), models.Index(fields=['error_category'], name='posts_logge_error_c_3a4a74_idx')],
            },
        ),
    ]
